import '../AutogeneratedForRentTest.dart'; 
import 'package:http/http.dart' as http;

class RentCommericalForRent {
  Future<List<Welcome>> getPosts(apiValue) async {
    print("ok NOOOOOOOt short term daily");
    final queryParameters = {
      'property-type': '$apiValue',
    };
    var url = Uri.https(
        'oxydu.com', '/wp-json/wp/v2/property-for-rent', queryParameters);

    try {
      final response = await http.get(url);
      if (response.statusCode == 200) { 
        final List<Welcome> listPosts =
            welcomeFromJson(response.body);
        print(response.body);
        return listPosts;
      } else {
        return <Welcome>[];
      }
    } catch (e) {
      return <Welcome>[];
    }
  }
}
