import 'package:http/http.dart' as http; 
import '../AutoGeneratedMotors.dart';

class ServiceMotors {
  Future<List<MotorsParse>> getPosts(apiValue) async {
    final queryParameters = {
      'motors-type': '$apiValue',
    };
    var url = Uri.https('oxydu.com', '/wp-json/wp/v2/motors', queryParameters);

    try {
      final response = await http.get(url);
      if (response.statusCode == 200) {
        final List<MotorsParse> listPosts = motorsParseFromJson(response.body);
        return listPosts;
      } else {
        return <MotorsParse>[];
      }
    } catch (e) {
      return <MotorsParse>[];
    }
  }
}
