import '../../AutogeneratedForSale.dart'; 
import 'package:http/http.dart' as http;

class ServiceForSale {
  Future<List<ForSale>> getPosts(apiValue) async {
  
    final queryParameters = {
      'property-type-sale': '$apiValue',
    };
    var url = Uri.https(
        'oxydu.com', '/wp-json/wp/v2/property-for-sale', queryParameters);

    try { 
      final response = await http.get(url);
      if (response.statusCode == 200) {
        final List<ForSale> listPosts =
            forSaleFromJson(response.body); 
        return listPosts;
      } else {
        return <ForSale>[];
      }
    } catch (e) {
      return <ForSale>[];
    }
  }
}