import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:oxydu/Data/ForRent/AutoGeneratedMotors.dart';
import 'package:sizer/sizer.dart';

class BuyItemMotorsStateManagement {
  Widget details(String title, String dataTitle) {
    var icondata = CupertinoIcons.tag_fill;

    // switch (position) {
    //   case 0:
    //     icondata = CupertinoIcons.tag_fill;

    //     break;
    //   case 1:
    //     icondata = CupertinoIcons.tag_fill;

    //     break;
    //   case 2:
    //     icondata = CupertinoIcons.tag_fill;

    //     break;
    //   case 3:
    //     icondata = Icons.check_box_outline_blank;

    //     break;
    // }

    return Column(children: [
      Row(children: [
        Icon(
          icondata,
          color: Colors.orange,
          size: 5.w,
        ),
        Text("\t$title", style: TextStyle(fontSize: 4.5.w)),
      ]),
      Row(
        mainAxisAlignment: MainAxisAlignment.end,
        children: [
          Text("$dataTitle\n",
              style: TextStyle(fontSize: 4.w, color: Colors.black45)),
        ],
      ),
      Divider(
        indent: 2,
        endIndent: 2,
        thickness: 0.4,
      )
    ]);
  }

  Widget itemDetailsMotorsUsedCars(
      int index, String title, List<MotorsParse> data) {
    return Column(children: [
      if (data[index].acf.yearOfManuf != null)
        details("Year", data[index].acf.yearOfManuf),
      if (data[index].acf.yearOfManuf != null)
        details("Km", data[index].acf.kilometersUsed),
      if (data[index].acf.doorsUsed != null)
        details("Doors", data[index].acf.doorsUsed),
      if (data[index].acf.colorUsed != null)
        details("Color", data[index].acf.colorUsed),
      if (data[index].acf.transmissionType != null)
        details("Transmission Type", data[index].acf.transmissionType),
      if (data[index].acf.finalDriveSystem != null)
        details("Final Drive System", data[index].acf.finalDriveSystem),
      // if (data[index].acf.sellerType != null)
      // details("Seller Type", data[index].acf.sellerType),
    ]);
  }
}
