import 'dart:ui';
import 'package:flutter/cupertino.dart';
import "package:flutter/material.dart";
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:localize_and_translate/localize_and_translate.dart';

import 'package:oxydu/Data/ForRent/AutoGeneratedMotors.dart';

import 'package:sizer/sizer.dart';

class MotorsStateManagement {
  Widget usedCars(
    double padding3,
    double paddding36,
    double paddding30,
    int substring3,
    List<MotorsParse> data,
    int index,
  ) {
    return Column(
      children: [
        Row(
          children: [
            Text("${translator.translate("Year")}",
                textAlign: TextAlign.left,
                style: new TextStyle(
                    fontSize: paddding36,
                    fontWeight: FontWeight.w600,
                    color: Colors.black)),
            if (data[index].acf.yearOfManuf != null)
              Text(data[index].acf.yearOfManuf,
                  overflow: TextOverflow.ellipsis,
                  textAlign: TextAlign.left,
                  style: new TextStyle(
                      fontSize: paddding36, color: Colors.grey[600])),
            //////////////////////////////////////
            // Text(
            //     widget.carModel.length > substring3
            //         ? widget.carModel.substring(0, substring3) + '...'
            //         : widget.carModel,
            //     overflow: TextOverflow.ellipsis,
            //     textAlign: TextAlign.left,
            //     style: new TextStyle(
            //         fontSize: paddding36, color: Colors.grey[600])),
            ///////////////////////////////
            Spacer(),
            SizedBox(
              height: 6.5.w,
              width: 6.5.w,
              child: IconButton(
                  padding: EdgeInsets.zero,
                  constraints: BoxConstraints(),
                  icon: Icon(FontAwesomeIcons.heart,
                      color: Colors.black, size: 6.5.w),
                  onPressed: () {}),
            ),
            SizedBox(width: paddding30),
            SizedBox(
              height: 7.w,
              width: 7.w,
              child: IconButton(
                  padding: EdgeInsets.zero,
                  constraints: BoxConstraints(),
                  icon:
                      Icon(Icons.flag_outlined, color: Colors.black, size: 7.w),
                  onPressed: () {}),
            ),
            SizedBox(width: 10),
          ],
        ),
        SizedBox(height: padding3),
        SizedBox(
            //width: paddding4,
            width: double.infinity,
            child: Row(
              children: [
                Text("${translator.translate("Km")}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        fontWeight: FontWeight.w600,
                        color: Colors.black)),
                //   Text("Km:${data[index].km}",
                Text("${data[index].acf.kilometersUsed}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        //fontWeight: FontWeight.bold,
                        color: Colors.grey[600])),
              ],
            )),
        SizedBox(height: padding3),
        SizedBox(
            //width: paddding4,
            width: double.infinity,
            child: Row(
              children: [
                Text("${translator.translate("Doors2")}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        fontWeight: FontWeight.w600,
                        color: Colors.black)),
                //   Text("Km:${data[index].km}",
                Text("${data[index].acf.doorsUsed}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        //fontWeight: FontWeight.bold,
                        color: Colors.grey[600])),
              ],
            )),
        SizedBox(height: padding3),
        SizedBox(
            //width: paddding4,
            width: double.infinity,
            child: Row(
              children: [
                Text("${translator.translate("Color2")}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        fontWeight: FontWeight.w600,
                        color: Colors.black)),
                //   Text("Km:${data[index].km}",
                Text("${data[index].acf.colorUsed}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        //fontWeight: FontWeight.bold,
                        color: Colors.grey[600])),
              ],
            ))
      ],
    );
  }

  Widget motorcycle(
    double padding3,
    double paddding36,
    double paddding30,
    int substring3,
    List<MotorsParse> data,
    int index,
  ) {
    return Column(
      children: [
        Row(
          children: [
            Text("${translator.translate("Year")}",
                textAlign: TextAlign.left,
                style: new TextStyle(
                    fontSize: paddding36,
                    fontWeight: FontWeight.w600,
                    color: Colors.black)),
            if (data[index].acf.yearOfManfMotorcycle != null)
              Text(
                  data[index].acf.yearOfManuf.length > substring3
                      ? data[index]
                              .acf
                              .yearOfManfMotorcycle
                              .substring(0, substring3) +
                          '...'
                      : data[index].acf.yearOfManfMotorcycle,
                  overflow: TextOverflow.ellipsis,
                  textAlign: TextAlign.left,
                  style: new TextStyle(
                      fontSize: paddding36, color: Colors.grey[600])),
            //////////////////////////////////////
            // Text(
            //     widget.carModel.length > substring3
            //         ? widget.carModel.substring(0, substring3) + '...'
            //         : widget.carModel,
            //     overflow: TextOverflow.ellipsis,
            //     textAlign: TextAlign.left,
            //     style: new TextStyle(
            //         fontSize: paddding36, color: Colors.grey[600])),
            ///////////////////////////////
            Spacer(),
            SizedBox(
              height: 6.5.w,
              width: 6.5.w,
              child: IconButton(
                  padding: EdgeInsets.zero,
                  constraints: BoxConstraints(),
                  icon: Icon(FontAwesomeIcons.heart,
                      color: Colors.black, size: 6.5.w),
                  onPressed: () {}),
            ),
            SizedBox(width: paddding30),
            SizedBox(
              height: 7.w,
              width: 7.w,
              child: IconButton(
                  padding: EdgeInsets.zero,
                  constraints: BoxConstraints(),
                  icon:
                      Icon(Icons.flag_outlined, color: Colors.black, size: 7.w),
                  onPressed: () {}),
            ),
            SizedBox(width: 10),
          ],
        ),
        SizedBox(height: padding3),
        SizedBox(
            //width: paddding4,
            width: double.infinity,
            child: Row(
              children: [
                Text("${translator.translate("Km")}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        fontWeight: FontWeight.w600,
                        color: Colors.black)),
                //   Text("Km:${data[index].km}",
                Text("${data[index].acf.kilometersMotorcycle}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        //fontWeight: FontWeight.bold,
                        color: Colors.grey[600])),
              ],
            )),
        SizedBox(height: padding3),
        SizedBox(
            //width: paddding4,
            width: double.infinity,
            child: Row(
              children: [
                Text("${translator.translate("Usage2")}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        fontWeight: FontWeight.w600,
                        color: Colors.black)),
                //   Text("Km:${data[index].km}",
                Text("${data[index].acf.usageMotorcycle}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        //fontWeight: FontWeight.bold,
                        color: Colors.grey[600])),
              ],
            )),
        SizedBox(height: padding3),
        SizedBox(
            //width: paddding4,
            width: double.infinity,
            child: Row(
              children: [
                Text("${translator.translate("Location2")}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        fontWeight: FontWeight.w600,
                        color: Colors.black)),
                //   Text("Km:${data[index].km}",
                Text("${data[index].acf.location}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        //fontWeight: FontWeight.bold,
                        color: Colors.grey[600])),
              ],
            ))
      ],
    );
  }

  Widget autoAccessories(
    double padding3,
    double paddding36,
    double paddding30,
    int substring3,
    List<MotorsParse> data,
    int index,
  ) {
    return Column(
      children: [
        Row(
          children: [
            Text("${translator.translate("Usage2")}",
                textAlign: TextAlign.left,
                style: new TextStyle(
                    fontSize: paddding36,
                    fontWeight: FontWeight.w600,
                    color: Colors.black)),
            if (data[index].acf.autoAccessoriesUsage != null)
              Text(
                  data[index].acf.autoAccessoriesUsage.length > substring3
                      ? data[index]
                              .acf
                              .autoAccessoriesUsage
                              .substring(0, substring3) +
                          '...'
                      : data[index].acf.autoAccessoriesUsage,
                  overflow: TextOverflow.ellipsis,
                  textAlign: TextAlign.left,
                  style: new TextStyle(
                      fontSize: paddding36, color: Colors.grey[600])),
            //////////////////////////////////////
            // Text(
            //     widget.carModel.length > substring3
            //         ? widget.carModel.substring(0, substring3) + '...'
            //         : widget.carModel,
            //     overflow: TextOverflow.ellipsis,
            //     textAlign: TextAlign.left,
            //     style: new TextStyle(
            //         fontSize: paddding36, color: Colors.grey[600])),
            ///////////////////////////////
            Spacer(),
            SizedBox(
              height: 6.5.w,
              width: 6.5.w,
              child: IconButton(
                  padding: EdgeInsets.zero,
                  constraints: BoxConstraints(),
                  icon: Icon(FontAwesomeIcons.heart,
                      color: Colors.black, size: 6.5.w),
                  onPressed: () {}),
            ),
            SizedBox(width: paddding30),
            SizedBox(
              height: 7.w,
              width: 7.w,
              child: IconButton(
                  padding: EdgeInsets.zero,
                  constraints: BoxConstraints(),
                  icon:
                      Icon(Icons.flag_outlined, color: Colors.black, size: 7.w),
                  onPressed: () {}),
            ),
            SizedBox(width: 10),
          ],
        ),
        SizedBox(height: padding3),
        SizedBox(
            //width: paddding4,
            width: double.infinity,
            child: Row(
              children: [
                Text("${translator.translate("condition")}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        fontWeight: FontWeight.w600,
                        color: Colors.black)),
                //   Text("Km:${data[index].km}",
                Text("${data[index].acf.autoAccessoriesCondition}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        //fontWeight: FontWeight.bold,
                        color: Colors.grey[600])),
              ],
            )),
        SizedBox(height: padding3),
        SizedBox(
            //width: paddding4,
            width: double.infinity,
            child: Row(
              children: [
                Text("${translator.translate("Location2")}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        fontWeight: FontWeight.w600,
                        color: Colors.black)),
                //   Text("Km:${data[index].km}",
                Text("${data[index].acf.location}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        //fontWeight: FontWeight.bold,
                        color: Colors.grey[600])),
              ],
            ))
      ],
    );
  }

  Widget heavyVehicles(
    double padding3,
    double paddding36,
    double paddding30,
    int substring3,
    List<MotorsParse> data,
    int index,
  ) {
    return Column(
      children: [
        Row(
          children: [
            Text("${translator.translate("Year")}",
                textAlign: TextAlign.left,
                style: new TextStyle(
                    fontSize: paddding36,
                    fontWeight: FontWeight.w600,
                    color: Colors.black)),
            if (data[index].acf.yearHeavyveh != null)
              Text(
                  data[index].acf.yearHeavyveh.length > substring3
                      ? data[index].acf.yearHeavyveh.substring(0, substring3) +
                          '...'
                      : data[index].acf.yearHeavyveh,
                  overflow: TextOverflow.ellipsis,
                  textAlign: TextAlign.left,
                  style: new TextStyle(
                      fontSize: paddding36, color: Colors.grey[600])),
            //////////////////////////////////////
            // Text(
            //     widget.carModel.length > substring3
            //         ? widget.carModel.substring(0, substring3) + '...'
            //         : widget.carModel,
            //     overflow: TextOverflow.ellipsis,
            //     textAlign: TextAlign.left,
            //     style: new TextStyle(
            //         fontSize: paddding36, color: Colors.grey[600])),
            ///////////////////////////////
            Spacer(),
            SizedBox(
              height: 6.5.w,
              width: 6.5.w,
              child: IconButton(
                  padding: EdgeInsets.zero,
                  constraints: BoxConstraints(),
                  icon: Icon(FontAwesomeIcons.heart,
                      color: Colors.black, size: 6.5.w),
                  onPressed: () {}),
            ),
            SizedBox(width: paddding30),
            SizedBox(
              height: 7.w,
              width: 7.w,
              child: IconButton(
                  padding: EdgeInsets.zero,
                  constraints: BoxConstraints(),
                  icon:
                      Icon(Icons.flag_outlined, color: Colors.black, size: 7.w),
                  onPressed: () {}),
            ),
            SizedBox(width: 10),
          ],
        ),
        SizedBox(height: padding3),
        SizedBox(
            //width: paddding4,
            width: double.infinity,
            child: Row(
              children: [
                Text("${translator.translate("Km")}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        fontWeight: FontWeight.w600,
                        color: Colors.black)),
                //   Text("Km:${data[index].km}",
                Text("${data[index].acf.kilometerHeavyveh}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        //fontWeight: FontWeight.bold,
                        color: Colors.grey[600])),
              ],
            )),
        SizedBox(height: padding3),
        SizedBox(
            //width: paddding4,
            width: double.infinity,
            child: Row(
              children: [
                Text("${translator.translate("Location2")}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        fontWeight: FontWeight.w600,
                        color: Colors.black)),
                //   Text("Km:${data[index].km}",
                Text("${data[index].acf.location}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        //fontWeight: FontWeight.bold,
                        color: Colors.grey[600])),
              ],
            ))
      ],
    );
  }

  Widget boat(
    double padding3,
    double paddding36,
    double paddding30,
    int substring3,
    List<MotorsParse> data,
    int index,
  ) {
    return Column(
      children: [
        Row(
          children: [
            Text("${translator.translate("age")}",
                textAlign: TextAlign.left,
                style: new TextStyle(
                    fontSize: paddding36,
                    fontWeight: FontWeight.w600,
                    color: Colors.black)),
            if (data[index].acf.age != null)
              Text(
                  data[index].acf.age.length > substring3
                      ? data[index].acf.age.substring(0, substring3) + '...'
                      : data[index].acf.age,
                  overflow: TextOverflow.ellipsis,
                  textAlign: TextAlign.left,
                  style: new TextStyle(
                      fontSize: paddding36, color: Colors.grey[600])),
            //////////////////////////////////////
            // Text(
            //     widget.carModel.length > substring3
            //         ? widget.carModel.substring(0, substring3) + '...'
            //         : widget.carModel,
            //     overflow: TextOverflow.ellipsis,
            //     textAlign: TextAlign.left,
            //     style: new TextStyle(
            //         fontSize: paddding36, color: Colors.grey[600])),
            ///////////////////////////////
            Spacer(),
            SizedBox(
              height: 6.5.w,
              width: 6.5.w,
              child: IconButton(
                  padding: EdgeInsets.zero,
                  constraints: BoxConstraints(),
                  icon: Icon(FontAwesomeIcons.heart,
                      color: Colors.black, size: 6.5.w),
                  onPressed: () {}),
            ),
            SizedBox(width: paddding30),
            SizedBox(
              height: 7.w,
              width: 7.w,
              child: IconButton(
                  padding: EdgeInsets.zero,
                  constraints: BoxConstraints(),
                  icon:
                      Icon(Icons.flag_outlined, color: Colors.black, size: 7.w),
                  onPressed: () {}),
            ),
            SizedBox(width: 10),
          ],
        ),
        SizedBox(height: padding3),
        SizedBox(
            //width: paddding4,
            width: double.infinity,
            child: Row(
              children: [
                Text("${translator.translate("Usage2")}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        fontWeight: FontWeight.w600,
                        color: Colors.black)),
                //   Text("Km:${data[index].km}",

                if (data[index].acf.usage176 != null)
                  Text(
                      data[index].acf.usage176.length > substring3+10
                          ? data[index].acf.usage176.substring(0, substring3+10) +
                              '...'
                          : data[index].acf.usage176,
                      overflow: TextOverflow.ellipsis,
                      textAlign: TextAlign.left,
                      style: new TextStyle(
                          fontSize: paddding36, color: Colors.grey[600]))
              ],
            )),
        SizedBox(height: padding3),
        SizedBox(
            //width: paddding4,
            width: double.infinity,
            child: Row(
              children: [
                Text("${translator.translate("condition")}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        fontWeight: FontWeight.w600,
                        color: Colors.black)), 
                        if (data[index].acf.condition != null)
                  Text(
                      data[index].acf.condition.length > substring3+10
                          ? data[index].acf.condition.substring(0, substring3+10) +
                              '...'
                          : data[index].acf.condition,
                      overflow: TextOverflow.ellipsis,
                      textAlign: TextAlign.left,
                      style: new TextStyle(
                          fontSize: paddding36, color: Colors.grey[600]))
              ],
            )),
        SizedBox(height: padding3),
        SizedBox(
            //width: paddding4,
            width: double.infinity,
            child: Row(
              children: [
                Text("${translator.translate("length2")}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        fontWeight: FontWeight.w600,
                        color: Colors.black)),
                //   Text("Km:${data[index].km}",
                Text("${data[index].acf.lengthlength}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        //fontWeight: FontWeight.bold,
                        color: Colors.grey[600])),
              ],
            ))
      ],
    );
  }

  Widget carforRent(
    double padding3,
    double paddding36,
    double paddding30,
    int substring3,
    List<MotorsParse> data,
    int index,
  ) {
    return Column(
      children: [
        Row(
          children: [
            Text("${translator.translate("CarType3")}",
                textAlign: TextAlign.left,
                style: new TextStyle(
                    fontSize: paddding36,
                    fontWeight: FontWeight.w600,
                    color: Colors.black)),
            if (data[index].acf.carType.length != null)
              Text(
                  data[index].acf.carType.length > substring3
                      ? data[index].acf.carType.substring(0, substring3) + '...'
                      : data[index].acf.carType,
                  overflow: TextOverflow.ellipsis,
                  textAlign: TextAlign.left,
                  style: new TextStyle(
                      fontSize: paddding36, color: Colors.grey[600])),
            //////////////////////////////////////
            // Text(
            //     widget.carModel.length > substring3
            //         ? widget.carModel.substring(0, substring3) + '...'
            //         : widget.carModel,
            //     overflow: TextOverflow.ellipsis,
            //     textAlign: TextAlign.left,
            //     style: new TextStyle(
            //         fontSize: paddding36, color: Colors.grey[600])),
            ///////////////////////////////
            Spacer(),
            SizedBox(
              height: 6.5.w,
              width: 6.5.w,
              child: IconButton(
                  padding: EdgeInsets.zero,
                  constraints: BoxConstraints(),
                  icon: Icon(FontAwesomeIcons.heart,
                      color: Colors.black, size: 6.5.w),
                  onPressed: () {}),
            ),
            SizedBox(width: paddding30),
            SizedBox(
              height: 7.w,
              width: 7.w,
              child: IconButton(
                  padding: EdgeInsets.zero,
                  constraints: BoxConstraints(),
                  icon:
                      Icon(Icons.flag_outlined, color: Colors.black, size: 7.w),
                  onPressed: () {}),
            ),
            SizedBox(width: 10),
          ],
        ),
        SizedBox(height: padding3),
        SizedBox(
            //width: paddding4,
            width: double.infinity,
            child: Row(
              children: [
                Text("${translator.translate("Location2")}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        fontWeight: FontWeight.w600,
                        color: Colors.black)),
                //   Text("Km:${data[index].km}",
                Text("${data[index].acf.location}",
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: paddding36,
                        //fontWeight: FontWeight.bold,
                        color: Colors.grey[600])),
              ],
            )),
      ],
    );
  }
}
