import 'package:dio/dio.dart';
import 'package:localize_and_translate/localize_and_translate.dart';
import 'package:oxydu/constants.dart';
class NotesServiceeForSale {
  static const headers = {
    'Authorization':
        'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvb3h5ZHUuY29tIiwiaWF0IjoxNjM1NjY3Nzg0LCJuYmYiOjE2MzU2Njc3ODQsImV4cCI6MTYzNjI3MjU4NCwiZGF0YSI6eyJ1c2VyIjp7ImlkIjoiMSJ9fX0.zNSI2jDA7NSrfYuyQYz0ohf5CX0PyQ4ZpOeHYZ7Q5d4'
    //'Content-Type]': 'application/json'
  }; 
  //update ==> put
  //delete ==> delete

  landForSale(
      dynamic price,
      dynamic title,
      dynamic description,
      dynamic phoneNumber,
      dynamic discount,
      dynamic sizeSQFT,
      dynamic url360,
      dynamic youTube,
      dynamic totalClosingFee,
      dynamic buyerTransferFee,
      dynamic propertyReferenceId,
      dynamic sellerTransferFee,
      dynamic listedBy,
      dynamic zonedFor,
      dynamic approvedBuildUpArea,
      dynamic areYouAlandLord,
      dynamic freeHold,
      dynamic location,
      dynamic landForSaleAPI,
      dynamic rERABrokerID,
      dynamic rERAlistercompany,
      dynamic rERApremitnumber,
      dynamic property) async { 

    Dio dio = new Dio();
    dio.options.headers["Authorization"] = "Bearer $s";
    var a = {};
    await dio.post('https://oxydu.com/wp-json/wp/v2/property-for-sale', data: {
      //'title': title,
      /* 'price_sale]': '$price',
      '_description]': '$description',
      'phone-number]': '$phoneNumber',
      'discount]': '$discount',
      'location]': '$location',*/
      'property-type-sale': '$landForSaleAPI',
      // '360-tour-url]': '$url360',
      // 'youtube-url]': '$youTube',
      /*'zone-for]': '$zonedFor',
      'approved-build-up-area-size]': '$approvedBuildUpArea',
      'free-hold-]': '$freeHold',
      'sqft-for-sale]': '$sizeSQFT',
      'total-closing-fee]': '$totalClosingFee',
      'property-reference-id]': '$propertyReferenceId',
      'buyer-transfer-fee]': '$buyerTransferFee',
      'seller-transfer-fee]': '$sellerTransferFee',
      'listed-by]': '$listedBy',
      'land-or-agent]': '$areYouAlandLord',*/
      'status': 'pending',
      'lang': '${translator.currentLanguage}'
    });
  }

  residentialBuilding(
    dynamic title,
    dynamic residentialBuildingAPI,
    dynamic residentialBuildingAPIchild,
    dynamic price,
    dynamic description,
    dynamic phoneNumber,
    dynamic discount,
    dynamic url360,
    dynamic youTube,
    dynamic developer,
    dynamic readBy,
    dynamic sizeSQFT,
    dynamic maintenanceFee,
    dynamic totalClosingFee,
    dynamic buyerTransferFee,
    dynamic sellerTransferFee,
    dynamic propertyReferenceId,
    dynamic annualCommunityFee,
    dynamic occupancyStatus,
    dynamic listedBy,
    dynamic zonedFor,
    dynamic bathroom,
    dynamic bedroom,
    dynamic building,
    dynamic areYouAlandLord,
    dynamic location,
    dynamic neighborHood,
    dynamic reralandLordName,
    dynamic property,
    dynamic reraTitleDeedNumber,
    dynamic reraPreRegistrationNumber,
    dynamic reraBrokerIdNumber,
    dynamic reraListerCompanyName,
    dynamic reraPremitNumber,
    dynamic reraAgentName,
  ) async {
    Dio dio = new Dio();
    dio.options.headers["Authorization"] = "Bearer $s";
    var a = {
      'title': '$title',
      'fields[price_sale]': '$price',
      'fields[_description]': '$description',
      'fields[phone-number]': '$phoneNumber',
      'fields[discount]': '$discount',
      'fields[location]': '$location',
      'property-type-sale':
          '$residentialBuildingAPI,$residentialBuildingAPIchild',
      "fields[developer]": '$developer',
      "fields[read-by-]": '$readBy',
      "fields[maintenance-fee]": '$maintenanceFee',
      "fields[annual-community-fee]": '$annualCommunityFee',
      "fields[occupancy-status-]": '$occupancyStatus',
      "fields[bathrooms-]": '$bathroom',
      "fields[bedrooms-]": '$bedroom',
      "fields[building]": '$building',
      'fields[360-tour-url]': '$url360',
      'fields[youtube-url]': '$youTube',
      'fields[zone-for]': '$zonedFor',
      'fields[sqft-for-sale]': '$sizeSQFT',
      'fields[total-closing-fee]': '$totalClosingFee',
      'fields[property-reference-id]': '$propertyReferenceId',
      'fields[buyer-transfer-fee]': '$buyerTransferFee',
      'fields[seller-transfer-fee]': '$sellerTransferFee',
      'fields[listed-by]': '$listedBy',
      'fields[land-or-agent]': '$areYouAlandLord',
      'status': 'pending',
      'lang': '${translator.currentLanguage}',
      'fields[rera-landlord-name]': '$reralandLordName',
      'fields[property]': '$property',
      'fields[rera-title-deed-number]': '$reraTitleDeedNumber',
      'fields[rera-pre-registration-number]': '$reraPreRegistrationNumber',
      'fields[rera-broker-id-number]': '$reraBrokerIdNumber',
      'fields[rera-lister-company-name]': '$reraListerCompanyName',
      'fields[rera-premit-number]': '$reraPremitNumber',
      'fields[rera-agent-name]': '$reraAgentName',
    };
    await dio
        .post('https://oxydu.com/wp-json/wp/v2/property-for-sale', data:FormData.fromMap(a));
  }

  multipleUnits(
    dynamic title,
    dynamic multipleUnitsAPI,
    dynamic price,
    dynamic description,
    dynamic phoneNumber,
    dynamic discount,
    dynamic url360,
    dynamic youTube,
    dynamic developer,
    dynamic readBy,
    dynamic sizeSQFT,
    dynamic maintenanceFee,
    dynamic totalClosingFee,
    dynamic buyerTransferFee,
    dynamic sellerTransferFee,
    dynamic propertyReferenceId,
    dynamic approvedBuildUpArea,
    dynamic occupancyStatus,
    dynamic listedBy,
    dynamic zonedFor,
    dynamic freeHold,
    dynamic building,
    dynamic areYouAlandLord,
    dynamic location,
    dynamic neighborHood,
    dynamic reralandLordName,
    dynamic property,
    dynamic reraTitleDeedNumber,
    dynamic reraPreRegistrationNumber,
    dynamic reraBrokerIdNumber,
    dynamic reraListerCompanyName,
    dynamic reraPremitNumber,
    dynamic reraAgentName,
  ) async {
    Dio dio = new Dio();
    dio.options.headers["Authorization"] = "Bearer $s";
    var a = {
      'title': title,
      'fields[price_sale]': '$price',
      'fields[_description]': '$description',
      'fields[phone-number]': '$phoneNumber',
      'fields[discount]': '$discount',
      'fields[location]': '$location',
      'property-type-sale': '$multipleUnitsAPI ',
      "fields[developer]": '$developer',
      "fields[read-by-]": '$readBy',
      "fields[maintenance-fee]": '$maintenanceFee',
      "fields[approved-build-up-area-size]": '$approvedBuildUpArea',
      "fields[occupancy-status-]": '$occupancyStatus',
      'fields[free-hold]': '$freeHold',
      "fields[building]": '$building',
      'fields[360-tour-url]': '$url360',
      'fields[youtube-url]': '$youTube',
      'fields[zone-for]': '$zonedFor',
      'fields[sqft-for-sale]': '$sizeSQFT',
      'fields[total-closing-fee]': '$totalClosingFee',
      'fields[property-reference-id]': '$propertyReferenceId',
      'fields[buyer-transfer-fee]': '$buyerTransferFee',
      'fields[seller-transfer-fee]': '$sellerTransferFee',
      'fields[listed-by]': '$listedBy',
      'fields[land-or-agent]': '$areYouAlandLord',
      'status': 'pending',
      'lang': '${translator.currentLanguage}',
      'fields[rera-landlord-name]': '$reralandLordName',
      'fields[property]': '$property',
      'fields[rera-title-deed-number]': '$reraTitleDeedNumber',
      'fields[rera-pre-registration-number]': '$reraPreRegistrationNumber',
      'fields[rera-broker-id-number]': '$reraBrokerIdNumber',
      'fields[rera-lister-company-name]': '$reraListerCompanyName',
      'fields[rera-premit-number]': '$reraPremitNumber',
      'fields[rera-agent-name]': '$reraAgentName',
    };
    await dio.post('https://oxydu.com/wp-json/wp/v2/property-for-sale', data:FormData.fromMap(a));
  }

  commercialForSale(
    dynamic title,
    dynamic commercialForSaleAPI,
    dynamic commercialForSaleAPIChild,
    dynamic price,
    dynamic description,
    dynamic phoneNumber,
    dynamic discount,
    dynamic url360,
    dynamic youTube,
    dynamic developer,
    dynamic readBy,
    dynamic sizeSQFT,
    dynamic maintenanceFee,
    dynamic totalClosingFee,
    dynamic buyerTransferFee,
    dynamic sellerTransferFee,
    dynamic propertyReferenceId,
    dynamic annualCommunityFee,
    dynamic occupancyStatus,
    dynamic listedBy,
    dynamic zonedFor,
    dynamic building,
    dynamic areYouAlandLord,
    dynamic location,
    dynamic neighborHood,
    dynamic reralandLordName,
    dynamic property,
    dynamic reraTitleDeedNumber,
    dynamic reraPreRegistrationNumber,
    dynamic reraBrokerIdNumber,
    dynamic reraListerCompanyName,
    dynamic reraPremitNumber,
    dynamic reraAgentName,
  ) async {
    Dio dio = new Dio();
    dio.options.headers["Authorization"] = "Bearer $s";
    var a = {
      'title': title,
      'fields[price_sale]': '$price',
      'fields[_description]': '$description',
      'fields[phone-number]': '$phoneNumber',
      'fields[discount]': '$discount',
      'fields[360-tour-url]': '$url360',
      'fields[youtube-url]': '$youTube',
      'fields[location]': '$location',
      'property-type-sale': '$commercialForSaleAPI,$commercialForSaleAPIChild',
      "fields[developer]": '$developer',
      "fields[read-by-]": '$readBy',
      'fields[sqft-for-sale]': '$sizeSQFT',
      "fields[maintenance-fee]": '$maintenanceFee',
      "fields[annual-community-fee]": '$annualCommunityFee',
      "fields[occupancy-status-]": '$occupancyStatus',
      "fields[building]": '$building',
      'fields[zone-for]': '$zonedFor',
      'fields[total-closing-fee]': '$totalClosingFee',
      'fields[property-reference-id]': '$propertyReferenceId',
      'fields[buyer-transfer-fee]': '$buyerTransferFee',
      'fields[seller-transfer-fee]': '$sellerTransferFee',
      'fields[listed-by]': '$listedBy',
      'fields[land-or-agent]': '$areYouAlandLord',
      'status': 'pending',
      'lang': '${translator.currentLanguage}',
      'fields[rera-landlord-name]': '$reralandLordName',
      'fields[property]': '$property',
      'fields[rera-title-deed-number]': '$reraTitleDeedNumber',
      'fields[rera-pre-registration-number]': '$reraPreRegistrationNumber',
      'fields[rera-broker-id-number]': '$reraBrokerIdNumber',
      'fields[rera-lister-company-name]': '$reraListerCompanyName',
      'fields[rera-premit-number]': '$reraPremitNumber',
      'fields[rera-agent-name]': '$reraAgentName',
    };
    await dio.post('https://oxydu.com/wp-json/wp/v2/property-for-sale', data:FormData.fromMap(a));
  }
}
