import 'package:http/http.dart' as http;

import 'AutoGeneratedJobsWanted.dart';

class ServiceJobsWanted {
  Future<List<JobsWantedParse>> getPosts(int x) async {
    final queryParameters = {
      'job-wanted-categories': '$x',
    };
    var url =
        Uri.https('oxydu.com', '/wp-json/wp/v2/want-job', queryParameters);
    try {
      final response = await http.get(url);
      if (response.statusCode == 200) {
        final List<JobsWantedParse> listPosts =
            jobsWantedParseFromJson(response.body);
        return listPosts;
      } else {
        return <JobsWantedParse>[];
      }
    } catch (e) {
      return <JobsWantedParse>[];
    }
  }
}
