/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String _kFontPkg = null;

  static const IconData home_appliances = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobiles = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motors = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData property_for_rent = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData property_for_sale = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business___industrial = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData classifieds = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData community = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData furniture___garden = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
